version: "3.6"
services:
  entity-core-db:
    build: .
    container_name: "entity-core-db"
    environment:
      - POSTGRES_USER=entitycore
      - POSTGRES_PASSWORD=entitycore
      - DB_NAME=entitycore
    networks:
      - entity-core
    ports:
      - "5432:5432"
  pgadmin:
    image: dpage/pgadmin4
    container_name: "pgadmin"
    environment:
      - PGADMIN_DEFAULT_EMAIL=hello@meda.co.uk
      - PGADMIN_DEFAULT_PASSWORD=entitycore
    volumes:
      - ./.pgadmin:/root/.pgadmin
    ports:
      - "5050:80"
    networks:
      - entity-core
networks:
  entity-core:
    name: entity-core
    driver: bridge
